version: "3.8"

services:
  vue:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "${PORT_CONTAINER_VUE}:${PORT_CONTAINER_VUE}"
    container_name: vue
    image: vue:latest
    command: ["npm", "run", "serve"]