version: "3.8"

services:
  vue:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    container_name: vue
    image: vue:latest
    command: ["npm", "run", "serve"]